name: Deploy ADF to Target Environment
 
on:
  workflow_dispatch:
  
jobs:
  deploy-adf:
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
 
    - name: Log in to Azure
      uses: azure/login@v2
      with:
        creds: '{"clientId":"${{ secrets.CLIENT_ID }}","clientSecret":"${{ secrets.CLIENT_SECRET }}","subscriptionId":"${{ secrets.SUBSCRIPTION_ID }}","tenantId":"${{ secrets.TENANT_ID }}"}'
 
    - name: Deploy ADF ARM template
      uses: azure/arm-deploy@v1
      with:
        scope: resourcegroup
        subscriptionId: ${{ secrets.SUBSCRIPTION_ID }}
        resourceGroupName: resourcegrp1
        template: yuvashree/ARMTemplateForFactory.json
        parameters: >
          yuvashree/ARMTemplateParametersForFactory.json
          factoryName=target-adf-devops
          location= East US
        deploymentName: adf-deployment-${{ github.run_number }}
